### ISSUE TITLE
Update to latest STLLoader

### ISSUE THREAD

**Issue by ammulder** [enspiral-cherubi/three-stl-loader#1]
The current Node module complains about XHRLoader !== FileLoader.  The original source has been updated accordingly:

https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/STLLoader.js

Can you roll a new Node module?

**Comment by data-doge** [comment]
hi @ammulder, 

just pushed a fix. lmk if that works for you.

**Comment by ammulder** [comment]
v1.0.5 works fine, thanks!
